#### Voted Majority for generating Ground truth from the annotations
- Author: Sushma Akoju, email: sushmaakoju@arizona.edu

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)
%cd gdrive/MyDrive/Colab\ Notebooks/natural\-logic
!ls

In [2]:
filename = "/content/gdrive/MyDrive/Colab Notebooks/natural-logic/example-annotation-round-1-2.xlsx"

In [3]:
import pandas as pd
import numpy as np

In [4]:
r1 =pd.read_excel(filename, sheet_name = "round1")
r2 =pd.read_excel(filename, sheet_name = "round2")

In [5]:
r1.head()

,Premise,Hypothesis,Mihai's Labels,Eduardo's label,Robert's labels,Haris's labels,Sushma's labels
0,an old man is sitting in a field,a man is sitting in a field,FE,FE,FE,FE,FE
1,every old man is sitting in a field,a man is sitting in a field,FE,FE,FE,FE,FE
2,an old man is sitting in a field,every man is sitting in a field,RE,RE,RE,RE,RE
3,every old man is sitting in a field,every man is sitting in a field,RE,RE,RE,RE,RE
4,some old man is sitting in a field,a man is sitting in a field,FE,Equivalence,FE,FE,FE

In [6]:
r2.head()

,Premise,Hypothesis,Mihai's Labels,Eduardo's label,Robert's labels,Haris's labels,Sushma's labels,FE,Unnamed: 8,Unnamed: 9
0,a boy is hitting a baseball,a child is hitting a baseball,FE,FE,FE,FE,FE,FE,FE,147.0
1,every boy is hitting a baseball,a child is hitting a baseball,FE,Neutral,FE,FE,FE,RE,RE,14.0
2,a boy is hitting a baseball,every child is hitting a baseball,RE,Neutral,RE,RE,RE,RE,Neutral,91.0
3,every boy is hitting a baseball,every child is hitting a baseball,RE,Neutral,RE,RE,FE,FE,Negation,5.0
4,some boy is hitting a baseball,a child is hitting a baseball,FE,FE,FE,FE,FE,FE,NaN,NaN

In [ ]:
r1 = r1.rename(columns={'Mihai\'s Labels':1, 'Eduardo\'s label':2, 'Robert\'s labels':3,
       'Haris\'s labels':4, 'Sushma\'s labels':5})
r1.columns

Index(['Premise', 'Hypothesis', 1, 2, 3, 4, 5], dtype='object')

In [ ]:
r2 = r2.rename(columns={'Mihai\'s Labels':1, 'Eduardo\'s label':2, 'Robert\'s labels':3,
       'Haris\'s labels':4, 'Sushma\'s labels':5})[['Premise', 'Hypothesis',            1,            2,            3,
                  4,            5,]]
r2.columns

Index(['Premise', 'Hypothesis', 1, 2, 3, 4, 5], dtype='object')

In [ ]:
r1.head()

,Premise,Hypothesis,1,2,3,4,5
0,an old man is sitting in a field,a man is sitting in a field,FE,FE,FE,FE,FE
1,every old man is sitting in a field,a man is sitting in a field,FE,FE,FE,FE,FE
2,an old man is sitting in a field,every man is sitting in a field,RE,RE,RE,RE,RE
3,every old man is sitting in a field,every man is sitting in a field,RE,RE,RE,RE,RE
4,some old man is sitting in a field,a man is sitting in a field,FE,Equivalence,FE,FE,FE

In [ ]:
label_map = {'FE':1, 'RE':2, 'Negation':3, 'Cover':4, 'Alternation':5, 'Equivalence':6, 'Neutral':7}

In [ ]:
for i in range(1,6):
  r1[i] = r1[i].map(label_map)
  r2[i] = r2[i].map(label_map)

In [ ]:
r1 = r1.dropna(axis='rows')
r1[1] = r1[1].astype('int')
r2 = r2.dropna(axis='rows')
r2[2] = r2[2].astype('int')

In [ ]:
r1.loc[0,][[1,2,3,4,5]].to_list()

[1, 1, 1, 1, 1]

In [ ]:
from collections import Counter
r1['Ground Truth'] = r1.apply(lambda x: Counter(x[[1,2,3,4,5]].to_list()).most_common()[0][0], axis=1)

In [ ]:
r1 = r1[['Premise','Hypothesis', 1,2,3,4,5,'Ground Truth']]
r1

,Premise,Hypothesis,1,2,3,4,5,label
0,an old man is sitting in a field,a man is sitting in a field,1,1,1,1,1,1
1,every old man is sitting in a field,a man is sitting in a field,1,1,1,1,1,1
2,an old man is sitting in a field,every man is sitting in a field,2,2,2,2,2,2
3,every old man is sitting in a field,every man is sitting in a field,2,2,2,2,2,2
4,some old man is sitting in a field,a man is sitting in a field,1,6,1,1,1,1
5,an old man is sitting in a field,some man is sitting in a field,1,1,1,1,1,1
6,some old man is sitting in a field,some man is sitting in a field,1,1,1,1,1,1
7,at least old man is sitting in a field,a man is sitting in a field,1,1,1,1,1,1
8,an old man is sitting in a field,at least man is sitting in a field,1,1,1,1,1,1
9,at least old man is sitting in a field,at least man is sitting in a field,1,1,1,1,1,1
10,not every old man is sitting in a field,a man is sitting in a field,7,7,1,7,1,7
11,an old man is sitting in a field,not every man is sitting in a field,7,7,7,7,7,7
12,not every old man is sitting in a field,not every man is sitting in a field,1,1,1,1,6,1
13,exactly one old man is sitting in a field,a man is sitting in a field,1,1,1,1,4,1
14,an old man is sitting in a field,exactly one man is sitting in a field,7,2,7,7,1,7
15,exactly one old man is sitting in a field,exactly one man is sitting in a field,1,7,1,7,1,1
16,all but one old man is sitting in a field,a man is sitting in a field,1,1,1,1,1,1
17,an old man is sitting in a field,all but one man is sitting in a field,7,2,2,7,2,2
18,all but one old man is sitting in a field,all but one man is sitting in a field,1,7,7,7,1,7
20,a bad old man is sitting in a field,a bad man is sitting in a field,1,1,1,6,1,1
22,an old man is not sitting in a field,a man is sitting in a field,7,7,7,4,3,7
23,an old man is sitting in a field,a man is not sitting in a field,3,7,7,3,3,3
24,an old man is not sitting in a field,a man is not sitting in a field,1,1,1,2,7,1
25,an old man is abnormally sitting in a field,a man is sitting in a field,1,1,1,1,1,1
26,an old man is sitting in a field,a man is abnormally sitting in a field,7,7,7,7,1,7
27,an old man is abnormally sitting in a field,a man is abnormally sitting in a field,1,2,1,1,1,1
28,an old man is elegantly sitting in a field,a man is sitting in a field,1,7,1,1,1,1
29,an old man is sitting in a field,a man is elegantly sitting in a field,7,7,7,7,1,7
30,an old man is elegantly sitting in a field,a man is elegantly sitting in a field,1,1,1,1,1,1
31,an old man is always sitting in a field,a man is sitting in a field,1,1,1,1,1,1
32,an old man is sitting in a field,a man is always sitting in a field,7,7,7,7,1,7
33,an old man is always sitting in a field,a man is always sitting in a field,1,1,1,1,7,1
34,an old man is never sitting in a field,a man is sitting in a field,7,7,7,4,7,7
35,an old man is sitting in a field,a man is never sitting in a field,3,7,7,3,7,7
36,an old man is never sitting in a field,a man is never sitting in a field,7,1,2,2,7,7

In [ ]:
r2[3] = r2[3].astype('int')
r2.loc[0,][[1,2,3,4,5]].to_list()

[1, 1, 1, 1, 1]

In [ ]:
r2['Ground Truth'] = r2.apply(lambda x: Counter(x[[1,2,3,4,5]].to_list()).most_common()[0][0], axis=1)
r2 = r2[['Premise','Hypothesis', 1,2,3,4,5,'Ground Truth']]
r2

,Premise,Hypothesis,1,2,3,4,5,label
0,a boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
1,every boy is hitting a baseball,a child is hitting a baseball,1,7,1,1,1,1
2,a boy is hitting a baseball,every child is hitting a baseball,2,7,2,2,2,2
3,every boy is hitting a baseball,every child is hitting a baseball,2,7,2,2,1,2
4,some boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
5,a boy is hitting a baseball,some child is hitting a baseball,1,1,1,1,1,1
6,some boy is hitting a baseball,some child is hitting a baseball,1,1,1,1,1,1
7,at least a boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
8,a boy is hitting a baseball,at least a child is hitting a baseball,1,1,1,1,1,1
9,at least a boy is hitting a baseball,at least a child is hitting a baseball,1,1,1,1,1,1
10,not every boy is hitting a baseball,a child is hitting a baseball,7,7,7,7,7,7
11,a boy is hitting a baseball,not every child is hitting a baseball,7,7,7,7,7,7
12,not every boy is hitting a baseball,not every child is hitting a baseball,1,1,1,1,1,1
13,exactly one boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
14,a boy is hitting a baseball,exactly one child is hitting a baseball,7,7,7,7,1,7
15,exactly one boy is hitting a baseball,exactly one child is hitting a baseball,1,1,7,7,1,1
16,all but one boy is hitting a baseball,a child is hitting a baseball,7,7,1,1,1,1
17,a boy is hitting a baseball,all but one child is hitting a baseball,7,7,2,7,7,7
18,all but one boy is hitting a baseball,all but one child is hitting a baseball,1,1,1,7,1,1
19,no boy is hitting a baseball,a child is hitting a baseball,7,7,7,7,7,7
21,no boy is hitting a baseball,no child is hitting a baseball,2,2,2,2,7,2
22,green boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
23,a boy is hitting a baseball,green child is hitting a baseball,7,7,7,7,7,7
24,green boy is hitting a baseball,green child is hitting a baseball,1,1,1,7,1,1
25,happy boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
26,a boy is hitting a baseball,happy child is hitting a baseball,7,7,7,7,7,7
27,happy boy is hitting a baseball,happy child is hitting a baseball,1,1,1,1,1,1
28,sad boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
29,a boy is hitting a baseball,sad child is hitting a baseball,7,7,7,7,7,7
30,sad boy is hitting a baseball,sad child is hitting a baseball,1,1,1,1,1,1
31,good boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
32,a boy is hitting a baseball,good child is hitting a baseball,7,7,7,7,7,7
33,good boy is hitting a baseball,good child is hitting a baseball,1,1,1,1,1,1
34,bad boy is hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
35,a boy is hitting a baseball,bad child is hitting a baseball,7,7,7,7,7,7
36,bad boy is hitting a baseball,bad child is hitting a baseball,1,1,1,1,1,1
37,a boy is not hitting a baseball,a child is hitting a baseball,7,7,7,7,7,7
38,a boy is hitting a baseball,a child is not hitting a baseball,7,7,7,7,3,7
39,a boy is not hitting a baseball,a child is not hitting a baseball,1,1,1,7,1,1
40,a boy is abnormally hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
41,a boy is hitting a baseball,a child is abnormally hitting a baseball,7,7,7,7,7,7
42,a boy is abnormally hitting a baseball,a child is abnormally hitting a baseball,1,1,1,1,1,1
43,a boy is elegantly hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
44,a boy is hitting a baseball,a child is elegantly hitting a baseball,7,7,7,7,7,7
45,a boy is elegantly hitting a baseball,a child is elegantly hitting a baseball,1,1,1,1,1,1
46,a boy is always hitting a baseball,a child is hitting a baseball,1,1,1,1,1,1
47,a boy is hitting a baseball,a child is always hitting a baseball,7,7,2,7,7,7
48,a boy is always hitting a baseball,a child is always hitting a baseball,1,1,1,1,1,1
49,a boy is never hitting a baseball,a child is hitting a baseball,7,7,7,7,7,7
51,a boy is never hitting a baseball,a child is never hitting a baseball,1,1,2,1,7,1

In [ ]:
import os
os.path.exists("/content/gdrive/MyDrive/Colab Notebooks/natural-logic/final-datasets/block-wise-data/blocks-dec26/")

True

In [ ]:
label_map = {1:'FE', 2:'RE', 3:'Negation', 4:'Cover', 5:'Alternation', 6:'Equivalence', 7:'Neutral'}
for i in range(1,6):
  r1[i] = r1[i].map(label_map)
  r2[i] = r2[i].map(label_map)
r1['Ground Truth'] = r1['Ground Truth'].map(label_map)
r2['Ground Truth'] = r2['Ground Truth'].map(label_map)

In [ ]:
r1 = r1.rename(columns={1:'Mihai\'s Labels', 2:'Eduardo\'s label', 3:'Robert\'s labels',
       4:'Haris\'s labels', 5:'Sushma\'s labels'})
r2 = r2.rename(columns={1:'Mihai\'s Labels', 2:'Eduardo\'s label', 3:'Robert\'s labels',
       4:'Haris\'s labels', 5:'Sushma\'s labels'})

In [ ]:
r1.head(), r2.head()

(                               Premise                       Hypothesis  \
 0     an old man is sitting in a field      a man is sitting in a field
 1  every old man is sitting in a field      a man is sitting in a field
 2     an old man is sitting in a field  every man is sitting in a field
 3  every old man is sitting in a field  every man is sitting in a field
 4   some old man is sitting in a field      a man is sitting in a field

   Mihai's Labels Eduardo's label Robert's labels Haris's labels  \
 0             FE              FE              FE             FE
 1             FE              FE              FE             FE
 2             RE              RE              RE             RE
 3             RE              RE              RE             RE
 4             FE     Equivalence              FE             FE

   Sushma's labels label
 0              FE    FE
 1              FE    FE
 2              RE    RE
 3              RE    RE
 4              FE    FE  ,
                            Premise                         Hypothesis  \
 0      a boy is hitting a baseball      a child is hitting a baseball
 1  every boy is hitting a baseball      a child is hitting a baseball
 2      a boy is hitting a baseball  every child is hitting a baseball
 3  every boy is hitting a baseball  every child is hitting a baseball
 4   some boy is hitting a baseball      a child is hitting a baseball

   Mihai's Labels Eduardo's label Robert's labels Haris's labels  \
 0             FE              FE              FE             FE
 1             FE         Neutral              FE             FE
 2             RE         Neutral              RE             RE
 3             RE         Neutral              RE             RE
 4             FE              FE              FE             FE

   Sushma's labels label
 0              FE    FE
 1              FE    FE
 2              RE    RE
 3              FE    RE
 4              FE    FE  )

In [55]:
r3 =pd.read_excel(filename, sheet_name = "round3")
r3.columns

Index(['SICK_id', 'Premise', 'Hypothesis', 'Modifier',
       'Premise/Hypothesis/Both', 'Part of Premise/Hypothesis Modified', 'M',
       'E', 'R', 'H', 'S', 'Ground Truth'],
      dtype='object')

In [56]:
r3.head()

,SICK_id,Premise,Hypothesis,Modifier,Premise/Hypothesis/Both,Part of Premise/Hypothesis Modified,M,E,R,H,S,Ground Truth
0,129.0,an old man is sitting in a field,a man is sitting in a field\n,NONE,NONE,NONE,FE,FE,FE,FE,FE,NaN
1,129.0,an old man is sitting in a good field,a man is sitting in a field\n,good,Premise,Object,FE,FE,FE,FE,FE,NaN
2,129.0,an old man is sitting in a field,a man is sitting in a good field,good,Hypothesis,Object,Neutral,Neutral,Neutral,Neutral,Neutral,NaN
3,129.0,an old man is sitting in a good field,a man is sitting in a good field,good,Both,Object,FE,FE,FE,FE,FE,NaN
4,129.0,an old man is sitting in all but one field,a man is sitting in a field\n,all but one,Premise,Object,Neutral,FE,FE,FE,Neutral,NaN

In [57]:
r3['SICK_id'] = r3['SICK_id'].astype('int')
label_map = {'FE':1, 'RE':2, 'Negation':3, 'Cover':4, 'Alternation':5, 'Equivalence':6, 'Neutral':7}
for i in ['M','E', 'R', 'H', 'S']:
  r3[i] = r3[i].map(label_map)

In [58]:
r3.head()

,SICK_id,Premise,Hypothesis,Modifier,Premise/Hypothesis/Both,Part of Premise/Hypothesis Modified,M,E,R,H,S,Ground Truth
0,129,an old man is sitting in a field,a man is sitting in a field\n,NONE,NONE,NONE,1,1,1,1,1,NaN
1,129,an old man is sitting in a good field,a man is sitting in a field\n,good,Premise,Object,1,1,1,1,1,NaN
2,129,an old man is sitting in a field,a man is sitting in a good field,good,Hypothesis,Object,7,7,7,7,7,NaN
3,129,an old man is sitting in a good field,a man is sitting in a good field,good,Both,Object,1,1,1,1,1,NaN
4,129,an old man is sitting in all but one field,a man is sitting in a field\n,all but one,Premise,Object,7,1,1,1,7,NaN

In [65]:
r3.loc[1,][[6,7,8,9,10]].to_list()

[1, 1, 1, 1, 1]

In [66]:
r3.loc[1,][['M','E', 'R', 'H', 'S']].to_list()

[1, 1, 1, 1, 1]

In [67]:
from collections import Counter
r3['Ground Truth'] = r3.apply(lambda x: Counter(x[['M','E', 'R', 'H', 'S']].to_list()).most_common()[0][0], axis=1)

In [68]:
label_map = {1:'FE', 2:'RE', 3:'Negation', 4:'Cover', 5:'Alternation', 6:'Equivalence', 7:'Neutral'}
for i in ['M','E', 'R', 'H', 'S']:
  r3[i] = r3[i].map(label_map)
r3['Ground Truth'] = r3['Ground Truth'].map(label_map)

In [69]:
r3.head()

,SICK_id,Premise,Hypothesis,Modifier,Premise/Hypothesis/Both,Part of Premise/Hypothesis Modified,M,E,R,H,S,Ground Truth
0,129,an old man is sitting in a field,a man is sitting in a field\n,NONE,NONE,NONE,FE,FE,FE,FE,FE,FE
1,129,an old man is sitting in a good field,a man is sitting in a field\n,good,Premise,Object,FE,FE,FE,FE,FE,FE
2,129,an old man is sitting in a field,a man is sitting in a good field,good,Hypothesis,Object,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
3,129,an old man is sitting in a good field,a man is sitting in a good field,good,Both,Object,FE,FE,FE,FE,FE,FE
4,129,an old man is sitting in all but one field,a man is sitting in a field\n,all but one,Premise,Object,Neutral,FE,FE,FE,Neutral,FE

In [70]:
writer = pd.ExcelWriter("/content/gdrive/MyDrive/Colab Notebooks/natural-logic/final-datasets/block-wise-data/blocks-dec26/data/example_annotations_gt.xlsx")
r1.to_excel(writer, sheet_name="round1")
r2.to_excel(writer, sheet_name="round2")
r3.to_excel(writer, sheet_name="round3")
writer.close()